# Foreground/Background
foreground            #b0b0b0
background            #121212
selection_foreground  #121212
selection_background  #b0b0b0
font_size 14.0
background_opacity 0.75

# Cursor
cursor                #b0b0b0
cursor_shape          block

# Standard Colors (Restored ANSI Palette)
color0  #1c1c1c
color8  #4d4d4d
color1  #ff5c5c
color9  #ff6e6e
color2  #b1e05f
color10 #bdf06d
color3  #f0c674
color11 #fff0a6
color4  #81a2be
color12 #9ec4e8
color5  #b294bb
color13 #cda8cd
color6  #8abeb7
color14 #a3ebe2
color7  #b0b0b0
color15 #ffffff

# Window Layout
window_padding_width 12
confirm_os_window_close 0
